### ISSUE TITLE
Validation error "cannot use fee without source" while createOrder

### ISSUE THREAD

**Issue by Kourin1996** [1inch/fusion-sdk#50]
Hello,

I executed the following code to understand what `createOrder` builds.

```ts
import {FusionSDK} from '@1inch/fusion-sdk'

async function main() {
    const sdk = new FusionSDK({
        url: 'https://api.1inch.dev/fusion',
        network: 1,
        authKey: '<AUTH_KEY>'
    });

    const {order, hash, quoteId} = await sdk.createOrder({
        fromTokenAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', // WETH
        toTokenAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', // USDC
        amount: '50000000000000000', // 0.05 ETH
        walletAddress: '0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
        fee: {
            takingFeeBps: 100,
            takingFeeReceiver: '0xD979df5BF656D45318D84670aF00a00e0a5e5A0c'
        },
    })

    console.log('debug::hash', hash);
    console.log('debug::order', order);
    console.log('debug::quoteId', quoteId);
}

main()
.then(() => process.exit(0))
.catch((err) => {
    console.error(err)
    process.exit(1)
})
```

But I've got the following result:

```txt
Error: cannot use fee without source
    at QuoterApi.<anonymous> (/.../1inch_test/node_modules/@1inch/src/api/quoter/quoter.api.ts:27:19)
    at Generator.next (<anonymous>)
    at /.../1inch_test/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/.../1inch_test/node_modules/tslib/tslib.js:114:16)
    at QuoterApi.getQuote (/.../1inch_test/node_modules/@1inch/fusion-sdk/api/quoter/quoter.api.js:17:24)
    at FusionApi.getQuote (/.../1inch_test/node_modules/@1inch/src/api/fusion-api.ts:65:31)
    at FusionSDK.<anonymous> (/.../1inch_test/node_modules/@1inch/src/sdk/sdk.ts:202:42)
    at Generator.next (<anonymous>)
    at /.../1inch_test/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/.../1inch_test/node_modules/tslib/tslib.js:114:16)
    at FusionSDK.getQuoteResult (/.../1inch_test/node_modules/@1inch/fusion-sdk/sdk/sdk.js:146:24)
    at FusionSDK.<anonymous> (/.../1inch_test/node_modules/@1inch/src/sdk/sdk.ts:104:34)
    at Generator.next (<anonymous>)
    at /.../bunzz/1inch_test/node_modules/tslib/tslib.js:118:75
```

The reason seems that QuoterRequest replace nullish `fee` with `sdk` which is rejected by its `validate` method.

https://github.com/1inch/fusion-sdk/blob/82b5b88682286924461786ab6f5dd8b83c077514/src/api/quoter/quoter.request.ts#L31

https://github.com/1inch/fusion-sdk/blob/82b5b88682286924461786ab6f5dd8b83c077514/src/api/quoter/quoter.request.ts#L70-L72

Then I added `source` in request and tried to run again, but I got another error.

```ts
    const {order, hash, quoteId} = await sdk.createOrder({
        fromTokenAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', // WETH
        toTokenAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', // USDC
        amount: '50000000000000000', // 0.05 ETH
        walletAddress: '0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
        fee: {
            takingFeeBps: 100,
            takingFeeReceiver: '0xD979df5BF656D45318D84670aF00a00e0a5e5A0c'
        },
        // Added the below line
        source: '0xD979df5BF656D45318D84670aF00a00e0a5e5A0c'
    })
```

The error seems to have failed because `source` was not allowed.

```txt
AxiosError: Request failed with status code 400
    at settle (/.../1inch_test/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/.../1inch_test/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:529:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      Authorization: 'Bearer RnuGwiQZK27C4w3aNt0HltGmvUCvcH8J',
      'User-Agent': 'axios/1.6.5',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://api.1inch.dev/fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.1inch.dev',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.1inch.dev',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 16,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Authorization: Bearer RnuGwiQZK27C4w3aNt0HltGmvUCvcH8J\r\n' +
      'User-Agent: axios/1.6.5\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.1inch.dev\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.1inch.dev/fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 48,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.1inch.dev',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.1inch.dev/fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: Object [AxiosHeaders] {
      date: 'Mon, 22 Jan 2024 01:48:45 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '74',
      connection: 'close',
      'access-control-allow-origin': '*',
      'content-security-policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
      'cross-origin-embedder-policy': 'require-corp',
      'cross-origin-opener-policy': 'same-origin',
      'cross-origin-resource-policy': 'same-origin',
      etag: 'W/"4a-alGG3++poHKz3858t9G3ieQTXS8"',
      'origin-agent-cluster': '?1',
      'referrer-policy': 'no-referrer',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-envoy-upstream-service-time': '13',
      'x-frame-options': 'SAMEORIGIN',
      'x-permitted-cross-domain-policies': 'none',
      'x-xss-protection': '0',
      'cf-cache-status': 'DYNAMIC',
      'set-cookie': [Array],
      server: 'cloudflare',
      'cf-ray': '849422f12c4b7118-YYZ'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'get',
      url: 'https://api.1inch.dev/fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: Bearer RnuGwiQZK27C4w3aNt0HltGmvUCvcH8J\r\n' +
        'User-Agent: axios/1.6.5\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.1inch.dev\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/fusion/quoter/v1.0/1/quote/receive/?fromTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=50000000000000000&walletAddress=0xd979df5bf656d45318d84670af00a00e0a5e5a0c&enableEstimate=true&fee=100&source=0xD979df5BF656D45318D84670aF00a00e0a5e5A0c',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.1inch.dev',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      statusCode: 400,
      message: 'source is not allowed',
      error: 'Bad Request'
    }
  }
}
```

I read the doc of the called endpoint (https://portal.1inch.dev/documentation/fusion/swagger/quoter?method=get&path=%2Fv1.0%2F1%2Fquote%2Freceive)

But there is no description of `source` What data should be inputted to `source`?

Thank you for your help.

## Environment

OS: macOR Ventura v13.3.1 (a)
Node: v18.18.2
@1inch/fusion-sdk: v0.1.13

**Comment by krboktv** [comment]
Hi! Just remove `fee` object from parameters. Or contact [csm@1inch.io](mailto:csm@1inch.io)
